language: go
go:
  - 1.6.3
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/Masterminds/glide
install:
  - glide install
  - go get -d $(glide nv)
script:
  - go install $(glide nv)
  - goveralls -service=travis-ci
